name: null
favicon: null
layout_spectrum: 0.7332885705400258
typography_spectrum: 0.287539599230513
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.41412124619819224
  lightness: 0.9942424260079861
  saturation: 0.7609345961827785
  rhythmicContrast: 0.4968822835944593
purpose: []
